<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>vb6c</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../VB6.Lexer/VB6.Lexer.csproj" />
    <ProjectReference Include="../VB6.Syntax/VB6.Syntax.csproj" />
  </ItemGroup>
</Project>
