<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>vb6c</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../VB6.Compiler/VB6.Compiler.csproj" />
    <ProjectReference Include="../VB6.ProjectSystem/VB6.ProjectSystem.csproj" />
  </ItemGroup>
</Project>
