namespace VB6.Syntax;

public static class SyntaxFacts
{
    public static SyntaxKind GetKeywordKind(string text) => text.ToUpperInvariant() switch
    {
        "OPTION" => SyntaxKind.OptionKeyword,
        "EXPLICIT" => SyntaxKind.ExplicitKeyword,
        "SUB" => SyntaxKind.SubKeyword,
        "FUNCTION" => SyntaxKind.FunctionKeyword,
        "DECLARE" => SyntaxKind.DeclareKeyword,
        "LIB" => SyntaxKind.LibKeyword,
        "ALIAS" => SyntaxKind.AliasKeyword,
        "ENUM" => SyntaxKind.EnumKeyword,
        "TYPE" => SyntaxKind.TypeKeyword,
        "END" => SyntaxKind.EndKeyword,
        "DIM" => SyntaxKind.DimKeyword,
        "REDIM" => SyntaxKind.ReDimKeyword,
        "PRESERVE" => SyntaxKind.PreserveKeyword,
        "ERASE" => SyntaxKind.EraseKeyword,
        "STATIC" => SyntaxKind.StaticKeyword,
        "CONST" => SyntaxKind.ConstKeyword,
        "AS" => SyntaxKind.AsKeyword,
        "BYTE" => SyntaxKind.ByteKeyword,
        "INTEGER" => SyntaxKind.IntegerKeyword,
        "LONG" => SyntaxKind.LongKeyword,
        "SINGLE" => SyntaxKind.SingleKeyword,
        "DOUBLE" => SyntaxKind.DoubleKeyword,
        "IF" => SyntaxKind.IfKeyword,
        "THEN" => SyntaxKind.ThenKeyword,
        "ELSEIF" => SyntaxKind.ElseIfKeyword,
        "ELSE" => SyntaxKind.ElseKeyword,
        "TRUE" => SyntaxKind.TrueKeyword,
        "FALSE" => SyntaxKind.FalseKeyword,
        "NOT" => SyntaxKind.NotKeyword,
        "AND" => SyntaxKind.AndKeyword,
        "OR" => SyntaxKind.OrKeyword,
        "XOR" => SyntaxKind.XorKeyword,
        "EQV" => SyntaxKind.EqvKeyword,
        "IMP" => SyntaxKind.ImpKeyword,
        "MOD" => SyntaxKind.ModKeyword,
        "LIKE" => SyntaxKind.LikeKeyword,
        "DEBUG" => SyntaxKind.DebugKeyword,
        "PRINT" => SyntaxKind.PrintKeyword,
        "CALL" => SyntaxKind.CallKeyword,
        "OPTIONAL" => SyntaxKind.OptionalKeyword,
        "BYREF" => SyntaxKind.ByRefKeyword,
        "BYVAL" => SyntaxKind.ByValKeyword,
        "FOR" => SyntaxKind.ForKeyword,
        "EACH" => SyntaxKind.EachKeyword,
        "IN" => SyntaxKind.InKeyword,
        "TO" => SyntaxKind.ToKeyword,
        "STEP" => SyntaxKind.StepKeyword,
        "NEXT" => SyntaxKind.NextKeyword,
        "WHILE" => SyntaxKind.WhileKeyword,
        "WEND" => SyntaxKind.WendKeyword,
        "DO" => SyntaxKind.DoKeyword,
        "LOOP" => SyntaxKind.LoopKeyword,
        "UNTIL" => SyntaxKind.UntilKeyword,
        "EXIT" => SyntaxKind.ExitKeyword,
        "SELECT" => SyntaxKind.SelectKeyword,
        "CASE" => SyntaxKind.CaseKeyword,
        "WITH" => SyntaxKind.WithKeyword,
        "IS" => SyntaxKind.IsKeyword,
        _ => SyntaxKind.IdentifierToken
    };
}
