namespace VB6.Syntax;

public enum SyntaxKind
{
    BadToken,
    EndOfFileToken,
    NewLineToken,

    IdentifierToken,
    IntegerLiteralToken,
    StringLiteralToken,

    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    BackslashToken,
    AmpersandToken,
    EqualsToken,
    LessToken,
    LessOrEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    LessGreaterToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    CommaToken,
    DotToken,
    ColonToken,

    OptionKeyword,
    ExplicitKeyword,
    SubKeyword,
    FunctionKeyword,
    EndKeyword,
    DimKeyword,
    AsKeyword,
    IntegerKeyword,
    IfKeyword,
    ThenKeyword,
    DebugKeyword,
    PrintKeyword,
    CallKeyword,
    ByRefKeyword,
    ByValKeyword,
    ForKeyword,
    ToKeyword,
    StepKeyword,
    NextKeyword,
    WhileKeyword,
    WendKeyword,
    DoKeyword,
    LoopKeyword,
    UntilKeyword,
    ExitKeyword,

    CompilationUnit,
    OptionExplicitStatement,
    SubDeclaration,
    FunctionDeclaration,
    Parameter,
    DimStatement,
    AssignmentStatement,
    IfStatement,
    ForStatement,
    WhileStatement,
    DoStatement,
    ExitStatement,
    DebugPrintStatement,
    InvocationStatement,
    SkippedStatement,
    LiteralExpression,
    NameExpression,
    InvocationExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression
}
